import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { fetchItems , addItem ,updateItem , deleteItem  } from './cartAPI';

const initialState = {
  items: [],
  status: 'idle',
};

// typically used to make async requests.
export const fetchAsync = createAsyncThunk(
  'cart/fetchItems',
  async () => {
    const response = await fetchItems();
    const data = await response.json()
    // console.log(data.data.user.carts);
    // The value we return becomes the `fulfilled` action payload
    return data.cart.items
  }
);

export const addAsync = createAsyncThunk(
  'cart/addItems',
  async (item) => {
    const response = await addItem(item);
    const data = await response.json();
   
    return data.cart.items
    // The value we return becomes the `fulfilled` action payload
    // return response.data;
  }
);

export const updateAsync = createAsyncThunk(
  'cart/updateItems',
  async ({item , count} )  => {
    console.log(item)
    console.log(count)
    const response = await updateItem(item , 120);
    const data = await response.json();
    console.log(data);
    return 1;
    // The value we return becomes the `fulfilled` action payload
    // return response.data;
  }
);

export const deleteAsync = createAsyncThunk(
  'cart/deleteItems',
  async (item )  => {
    console.log(item)
    const response = await deleteItem(item);
    const data = await response.json();
    return data.cart.items
   
    // The value we return becomes the `fulfilled` action payload
    // return response.data;
  }
);

export const cartSlice = createSlice({
  name: 'cart',
  initialState,
  reducers: {
   
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchAsync.fulfilled , (state , action) =>{
        console.log(action.payload)
        state.items = action.payload;
      })
      .addCase(addAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.items= (action.payload);
      })
      .addCase(updateAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.items= (action.payload);
        // state.items.push(action.payload);
      })
      .addCase(deleteAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.items= (action.payload);
        // state.items.push(action.payload);
      });
  },
});

// export const {  } = productsSlice.actions;




export default cartSlice.reducer;